# generated by fastapi-codegen:
#   filename:  openapi.yaml
#   timestamp: 2025-06-28T15:02:02+00:00



import argparse
import json
import os
from typing import *
from typing import Optional, Union

from autogen.mcp.mcp_proxy import MCPProxy
from autogen.mcp.mcp_proxy.security import APIKeyHeader, BaseSecurity

from models import (
    EpfscCertificatePostRequest,
    EpfscCertificatePostResponse,
    EpfscCertificatePostResponse1,
    EpfscCertificatePostResponse2,
    EpfscCertificatePostResponse3,
    EpfscCertificatePostResponse4,
    EpfscCertificatePostResponse5,
    EpfscCertificatePostResponse6,
    PecerCertificatePostRequest,
    PecerCertificatePostResponse,
    PecerCertificatePostResponse1,
    PecerCertificatePostResponse2,
    PecerCertificatePostResponse3,
    PecerCertificatePostResponse4,
    PecerCertificatePostResponse5,
    PecerCertificatePostResponse6,
    UncrdCertificatePostRequest,
    UncrdCertificatePostResponse,
    UncrdCertificatePostResponse1,
    UncrdCertificatePostResponse2,
    UncrdCertificatePostResponse3,
    UncrdCertificatePostResponse4,
    UncrdCertificatePostResponse5,
    UncrdCertificatePostResponse6,
)

app = MCPProxy(
    description="Pension Payment Order and UAN, as provided by EPFO (https://www.epfindia.gov.in), can be downloaded in citizen's DigiLocker account.",
    termsOfService='https://apisetu.gov.in/terms.php',
    title="Employees' Provident Fund Organization",
    version='3.0.0',
    servers=[{'url': 'https://apisetu.gov.in/epfindia/v3'}],
)


@app.post(
    '/epfsc/certificate',
    description=""" API to verify Scheme Certificate. """,
    tags=['certificate_generation'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def epfsc(body: EpfscCertificatePostRequest = None):
    """
    Scheme Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/pecer/certificate',
    description=""" API to verify Pension Certificate. """,
    tags=['certificate_generation'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def pecer(body: PecerCertificatePostRequest = None):
    """
    Pension Certificate
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


@app.post(
    '/uncrd/certificate',
    description=""" API to verify UAN Card. """,
    tags=['certificate_generation'],
    security=[
        APIKeyHeader(name="X-APISETU-APIKEY"),
        APIKeyHeader(name="X-APISETU-CLIENTID"),
    ],
)
def uncrd(body: UncrdCertificatePostRequest = None):
    """
    UAN Card
    """
    raise RuntimeError("Should be patched by MCPProxy and never executed")


if __name__ == "__main__":
    parser = argparse.ArgumentParser(description="MCP Server")
    parser.add_argument(
        "transport",
        choices=["stdio", "sse", "streamable-http"],
        help="Transport mode (stdio, sse or streamable-http)",
    )
    args = parser.parse_args()

    if "CONFIG_PATH" in os.environ:
        config_path = os.environ["CONFIG_PATH"]
        app.load_configuration(config_path)

    if "CONFIG" in os.environ:
        config = os.environ["CONFIG"]
        app.load_configuration_from_string(config)

    if "SECURITY" in os.environ:
        security_params = BaseSecurity.parse_security_parameters_from_env(
            os.environ,
        )

        app.set_security_params(security_params)

    mcp_settings = json.loads(os.environ.get("MCP_SETTINGS", "{}"))

    app.get_mcp(**mcp_settings).run(transport=args.transport)
